version: '3.8'
name: 'modul-165'

services:
  couchdb:
    image: couchdb:3.3
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
    volumes:
      - couchdb_data:/opt/couchdb/data
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://admin:password@couchdb:5984/_up || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  server:
    build: server/.
    env_file:
      - server/.env
    ports:
      - "3001:3000"
    depends_on:
      couchdb:
        condition: service_healthy

#  frontend:
#    build: client/.
#    ports:
#      - "3000:3000"
#    depends_on:
#      couchdb:
#        condition: service_healthy


volumes:
  couchdb_data: {}
