name: 'modul-165'

services:
  couchdb:
    image: couchdb:3.3
    container_name: couchdb
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
    volumes:
      - couchdb_data:/opt/couchdb/data
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://admin:password@couchdb:5984/_up || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - appnet

  backend:
    build:
      context: ./server
    container_name: express-backend
    env_file:
      - ./server/.env
    ports:
      - "3001:3000"
    depends_on:
      couchdb:
        condition: service_healthy
    networks:
      - appnet

  frontend:
    build:
      context: ./client
    container_name: next-frontend
    env_file:
      - ./client/.env
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - appnet

networks:
  appnet:
    driver: bridge

volumes:
  couchdb_data: {}